# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_IsoDeconvMM_rcpparma_hello_world', PACKAGE = 'IsoDeconvMM')
}

rcpparma_outerproduct <- function(x) {
    .Call('_IsoDeconvMM_rcpparma_outerproduct', PACKAGE = 'IsoDeconvMM', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_IsoDeconvMM_rcpparma_innerproduct', PACKAGE = 'IsoDeconvMM', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_IsoDeconvMM_rcpparma_bothproducts', PACKAGE = 'IsoDeconvMM', x)
}

